---
- name: build network automation inventory report
  hosts: LabGroup
  gather_facts: False


  tasks:
    - name: RETRIEVE FACTS
      include_role:
        name: "{{ansible_network_os}}"
        tasks_from: get_facts.yml
      when: ansible_network_os is defined

- name: build network automation inventory report
  hosts: localhost
  gather_facts: False

  vars:
    file_path: /var/www/html/index.html

  tasks:

    - name: create HTML report
      become: yes
      template:
        src: report.j2
        dest: "{{ file_path }}"

    - name: DISPLAY LINK TO INVENTORY REPORT
      debug:
        msg: "Please go to http://{{hostvars['localhost'].ansible_host}}:8888"
